id: IC7F39AF4
ocr_import_info:
  timestamp: '2023-09-28T04:49:42.933278+00:00'
  batch_id: batch-fc26
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.11
  sponsor: Dharma Kyab
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-09-28 16:51:57.881818+00:00
last_modified: 2023-09-28 16:51:57.881825+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W3CN4786
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW3CN4786
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: བསླབ་པ་ཀུན་ལས་བཏུས་པའི་ཚིག་ལེའུར་བྱས་པ།
  languages:
  - bo
  author: རྒྱལ་སྲས་ཞི་བ་ལྷ།
statistics:
  ocr_word_mean_confidence_index: 0.9978904758909193
  ocr_word_median_confidence_index: 1.0
bases:
  I3CN4788:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN4788
      total_pages: 474
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I3CN4788.txt
    statistics:
      ocr_word_median_confidence_index: 1.0
      ocr_word_mean_confidence_index: 0.9978904758909193
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
